name: Deploy to GitHub Pages

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          cache: yarn

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20 

      - name: Ensure Yarn 3.6.4
        run: corepack enable

      - name: Install Dependencies
        run: |
          corepack enable
          yarn install --immutable
        env:
          YARN_ENABLE_GLOBAL_CACHE: 1
          YARN_ENABLE_IMMUTABLE_INSTALLS: 1

      - name: Build
        run: yarn build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          external_repository: nolansmug/nolansmug.github.io
          publish_dir: ./build
          publish_branch: main
          keep_files: false